### ISSUE TITLE
Needs pull_request_target for forks to work.

### ISSUE THREAD

**Issue by robdodson** [brown-ccv/alex-recommends#5]
I noticed when folks forked our repo and this action ran it would break saying:

```
##[error]Resource not accessible by integration
```

I think the fix is to instruct people to use the `pull_request_target` workflow event instead of `pull_request` to trigger this Action.
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

I _think_ this is needed because alex-recommends needs elevated permissions to post a comment. I tried to explain a bit more in this thread: https://github.com/GoogleChrome/web.dev/issues/3705

**Comment by mcmcgrath13** [comment]
Thanks - I dint't know about that! I've updated the example on trunk and it looks like that's now updated in the marketplace listing.
